import exceptions
class Exception(exceptions.Exception):
    pass
